apiVersion: v2
appVersion: v1.0.3
description: A Helm chart for Gatekeeper Policy Manager, a simple to use, read-only
  web UI for viewing OPA Gatekeeper policies' status in a Kubernetes Cluster.
home: https://sighup.io
icon: https://raw.githubusercontent.com/sighupio/gatekeeper-policy-manager/master/app/static-content/logo.svg
keywords:
- opa
- gatekeeper
- policy
- ui
- dashboard
- web
- rego
- webapp
maintainers:
- email: ramiro@sighup.io
  name: Ramiro Algozino
- email: alessio.pragliola@sighup.io
  name: Alessio Pragliola
name: gatekeeper-policy-manager
sources:
- https://github.com/sighupio/gatekeeper-policy-manager/
type: application
version: 0.4.1
