apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dpop-rs
  namespace: applications
  annotations:
    cert-manager.io/cluster-issuer: vault-pki-int
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dpop-rs.192.168.50.10.nip.io
      secretName: dpop-rs-tls
  rules:
    - host: dpop-rs.192.168.50.10.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dpop-rs
                port:
                  number: 80
