apiVersion: v1
kind: Service
metadata:
  name: uma-rs
  namespace: applications
  labels:
    app.kubernetes.io/name: uma-rs
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: uma-rs
